language: php

language: php

sudo: false

matrix:
  include:
  - php: 5.6
  - php: 5.6
  - php: 5.6
  - php: 5.6
  - php: 5.5
  - php: 5.4
  - php: 5.3
  - php: 5.2
  - php: hhvm
  - php: 7.0
  allow_failures:
  - php: hhvm
  fast_finish: true
env:
    - WP_VERSION=master # Git equivalent of SVN /trunk

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

# Before install, failures in this section will result in build status 'errored'
before_install:
    # setup WP_DEVELOP_DIR (needed for bbPress to bootstrap WP PHPUnit tests)
    - WP_DEVELOP_DIR=/tmp/wordpress
    # clone the WordPress develop repo
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
    - WP_DEVELOP_DIR=/tmp/wordpress/src

