language: php

php:
  include:
  - php: 5.5
    env: WP_TRAVISCI=travis:js
  - php: 5.2
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.3
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: hhvm

env:
    - WP_VERSION=master # Git equivalent of SVN /trunk

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

# Before install, failures in this section will result in build status 'errored'
before_install:
    # setup WP_DEVELOP_DIR (needed for bbPress to bootstrap WP PHPUnit tests)
    - WP_DEVELOP_DIR=/tmp/wordpress
    # clone the WordPress develop repo
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
    - WP_DEVELOP_DIR=/tmp/wordpress/src

